# fly.toml app configuration file generated for my-telegram-bot--wdpqa on 2026-06-04T11:41:59Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-telegram-bot--wdpqa'
primary_region = 'iad'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  dockerfile = 'Dockerfile'

[env]
  APP_MODE = 'personal'
  BOT_TOKEN = ''
  CONTACT_URL = 'https://t.me/DevSculpt'
  DEMO_CHANNEL_EN = 'https://t.me/DevSculptChannel'
  DEMO_CHANNEL_FR = 'https://t.me/DevSculptChannel'
  MAX_SCHEDULER_DURATION_MINUTES = '1440'
  MIN_SCHEDULER_INTERVAL = '10'
  OWNER_ID = ''
  TIMEZONE_OFFSET = '+03:00'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
