# texts.py

TEXTS = {
    "fr": {
        "back": "🔙 Retour",
        "cancel": "Annuler",
        "save": "Enregistrer",
        "edit": "✏️ Modifier",
        "view": "👁️ Voir",
        "activate": "Activer",
        "deactivate": "Désactiver",
        "enabled": "✅ Activé",
        "disabled": "❌ Désactivé",
        "keep_current": "✅ Continuer",
        "validate_selection": "✅ Valider la sélection",
        "terminate_edit": "✅ Terminer les modifications",
        "select_all": "✅ Tout sélectionner",
        "deselect_all": "❌ Tout désélectionner",
        "confirm_yes": "✅ Oui",
        "confirm_no": "❌ Non",
        "success": "✅ Succès",
        "error": "❌ Erreur",
        "delete_confirm": "Supprimer {count} élément(s) ?",
        "delete_selected_button": "🗑 Supprimer la sélection ({count})",
        "status_label": "État :",
        "trial_started": "✅ Votre essai gratuit de {days} jours est activé !\nIl se termine le {end_date}.\n\nProfitez bien du bot !",
        "menu_prompt": "Choisissez une option :",
        "trial_expired": "⏰ Votre période d'essai de 3 jours est terminée.\n\nPour continuer à utiliser le bot, contactez @DevSculpt pour obtenir votre licence permanente.\n\nMerci de votre intérêt !",
        "main_menu_welcome": "Bienvenue ! Choisissez une option :",
        "main_menu_group_mgmt": "👥 Gérer des groupes",
        "main_menu_scheduled": "📅 Planifier des envois",
        "main_menu_reminders": "⏰ Créer des rappels",
        "group_config_choice": "Sélectionnez le type de configuration :",
        "group_config_welcome": "💬 Message de bienvenue",
        "group_config_antispam": "🛡 Protection anti-spam",
        "group_list_title": "Vos groupes éligibles :",
        "group_list_empty": "Aucun groupe éligible trouvé.",
        "group_list_refresh": "🔄 Rafraîchir",
        "welcome_config_title": "Configuration du message de bienvenue : {group}",
        "welcome_edit_button": "✏️ Modifier le message",
        "welcome_edit_prompt": "✏️ Message de bienvenue pour {group}\nVariables : {{username}} (nom), {{group_name}} (groupe).\nEntrez le nouveau message :",
        "welcome_current_message": "État : {status}\nMessage : \"{message}\"",
        "welcome_status_enabled": "✅ Activé",
        "welcome_status_disabled": "❌ Désactivé",
        "antispam_config_title": "🛡 Anti‑spam : {group}",
        "antispam_block_links": "  🔗  Bloquer les liens",
        "antispam_block_repeated": "🔁 Bloquer les répétitions",
        "antispam_status_enabled": "✅ Activé",
        "antispam_status_disabled": "❌ Désactivé",
        "scheduler_main_title": "📅 Messages programmés\nChoisissez une action :",
        "scheduler_main_create": "  ➕ Nouveau message programmé",
        "scheduler_main_edit": "✍️ Modifier un message programmé",
        "scheduler_main_delete": "🗑️ Supprimer un message programmé",
        "scheduler_create_group_select": "Sélectionnez les groupes cibles :",
        "scheduler_create_text_prompt": "✏️ Veuillez entrer le texte du message programmé :",
        "scheduler_create_interval_prompt": "⏱️ Veuillez entrer l'intervalle entre chaque envoi (en minutes) :\nMinimum : {minimum} minutes.",
        "scheduler_create_count_prompt": "🔢 Veuillez entrer le nombre d'envois maximum :\n⚠️ Arrêt automatique après 24 heures, même si le nombre n'est pas atteint.",
        "scheduler_confirm_text": "📋 Récapitulatif de la programmation\n\n📌 Destination : {destination}\n💬 Message : \"{text}\"\n⏱️ Intervalle : {interval} min\n🔢 Nombre d'envois max : {count}\n\n⚠️ Arrêt automatique après 24 heures.\nConfirmez-vous l'enregistrement ?",
        "scheduler_confirm_destination": "{count} groupe(s) sélectionné(s)",
        "scheduler_confirm_create_button": "✅ Confirmer l'envoi",
        "scheduler_confirm_edit_button": "✅ Enregistrer les modifications",
        "scheduler_edit_list_title": "📋 Messages programmés en cours :",
        "scheduler_edit_list_empty": "Aucun message programmé.",
        "scheduler_edit_item_summary": "{text} ({interval}min, {sent}/{max_sends}, {group_count} groupe(s))",
        "scheduler_edit_text_prompt": "✏️ Texte actuel : \"{current}\"\nEntrez un nouveau texte ou appuyez sur Continuer.",
        "scheduler_edit_interval_prompt": "⏱️ Intervalle actuel : {current} min\nEntrez un nouvel intervalle ou appuyez sur Continuer.",
        "scheduler_edit_count_prompt": "🔢 Nombre d'envois actuel : {current}\nEntrez un nouveau nombre ou appuyez sur Continuer.\n⚠️ Arrêt automatique après 24 heures, même si le nombre n'est pas atteint.",
        "scheduler_delete_list_title": "🗑 Sélectionnez les messages à supprimer :",
        "scheduler_delete_list_empty": "Aucun message programmé à supprimer.",
        "scheduler_delete_item_summary": "{text} ({interval}min, {sent}/{max_sends}, {group_count} grp)",
        "reminder_main_title": "⏰ Rappels\nChoisissez une action :",
        "reminder_main_create": "  ➕ Nouveau rappel",
        "reminder_main_edit": "✍️ Modifier un rappel",
        "reminder_main_delete": "🗑️ Supprimer un rappel",
        "reminder_mode_prompt": "Sélectionnez le mode d'envoi du rappel :",
        "reminder_mode_private": "📩 Envoi privé",
        "reminder_mode_groups": "👥 Envoi groupé",
        "reminder_group_select": "Sélectionnez les groupes cibles pour le rappel :",
        "reminder_datetime_prompt": "📅 Veuillez entrer la date et l'heure du premier rappel (format AAAA-MM-JJ HH:MM , heure locale) :",
        "reminder_edit_datetime_prompt": "📅 Date actuelle : {current}\nEntrez une nouvelle date (AAAA-MM-JJ HH:MM) ou appuyez sur Continuer.",
        "reminder_recurrence_prompt": "🔄 Sélectionnez la récurrence du rappel :",
        "reminder_edit_recurrence_prompt": "🔄 Récurrence actuelle : {current}\nChoisissez une nouvelle récurrence ou appuyez sur Continuer.",
        "reminder_recurrence_daily": "📆 Quotidien",
        "reminder_recurrence_weekly": "📅 Hebdomadaire",
        "reminder_recurrence_monthly": "🗓 Mensuel",
        "reminder_recurrence_once": "1️⃣ Une seule fois",
        "reminder_recurrence_short_daily": "Quot.",
        "reminder_recurrence_short_weekly": "Hebdo.",
        "reminder_recurrence_short_monthly": "Mens.",
        "reminder_recurrence_short_once": "1 fois",
        "reminder_text_prompt": "✏️ Veuillez entrer le texte du rappel :",
        "reminder_edit_text_prompt": "✏️ Texte actuel : \"{current}\"\nEntrez un nouveau texte ou appuyez sur Continuer.",
        "reminder_confirm_text": "📋 Récapitulatif du rappel\n\n📌 Destination : {dest}\n💬 Message : \"{text}\"\n📅 Première occurrence : {datetime}\n🔄 Récurrence : {recurrence}\n\nConfirmez-vous l'enregistrement ?",
        "reminder_dest_private": "Envoi privé",
        "reminder_dest_groups": "{count} groupe(s) sélectionné(s)",
        "reminder_confirm_create_button": "✅ Confirmer",
        "reminder_confirm_edit_button": "✅ Enregistrer les modifications",
        "reminder_edit_list_title": "📋 Rappels en cours :",
        "reminder_edit_list_empty": "Aucun rappel enregistré.",
        "reminder_delete_list_title": "🗑 Sélectionnez les rappels à supprimer :",
        "reminder_delete_list_empty": "Aucun rappel à supprimer.",
        "reminder_delete_item_summary": "{text} ({rec}, {date}, {dest})",
        "success_welcome_updated": "✅ Message de bienvenue mis à jour avec succès !",
        "success_scheduler_created": "✅ Message programmé enregistré avec succès !",
        "success_scheduler_edited": "✏️ Message programmé modifié avec succès !",
        "success_scheduler_deleted": "🗑 Message(s) programmé(s) supprimé(s) avec succès !",
        "success_reminder_created": "✅ Rappel enregistré avec succès !",
        "success_reminder_edited": "✏️ Rappel modifié avec succès !",
        "success_reminder_deleted": "🗑 Rappel(s) supprimé(s) avec succès !",
        "error_interval_minimum": "❌ Veuillez entrer un nombre entier >= 10 minutes.",
        "error_count_positive": "❌ Veuillez entrer un nombre entier positif.",
        "error_datetime_format": "❌ Date invalide ou déjà passée. Utilisez le format AAAA-MM-JJ HH:MM (ex: 2026-05-15 14:30).",
        "error_no_eligible_groups": "Aucun groupe éligible trouvé.",
        "error_incomplete_data": "Données incomplètes.",
        "error_no_selection": "Veuillez sélectionner au moins un groupe.",
        "error_message_not_found": "Message introuvable.",
        "error_no_selection_message": "Aucun message sélectionné.",
        "error_reminder_not_found": "Rappel introuvable.",
        "error_no_reminder_selected": "Aucun rappel sélectionné.",
        "error_unknown_recurrence": "Récurrence inconnue.",
        "error_date_past": "La date est déjà passée. Veuillez entrer une date future.",
        "welcome_default": "Bienvenue {username} !"
    },
    "en": {
        "back": "🔙 Back",
        "cancel": "Cancel",
        "save": "Save",
        "edit": "✏️ Edit",
        "view": "👁️ View",
        "activate": "Activate",
        "deactivate": "Deactivate",
        "enabled": "✅ Enabled",
        "disabled": "❌ Disabled",
        "keep_current": "✅ Continue",
        "validate_selection": "✅ Confirm Selection",
        "terminate_edit": "✅ Finish Editing",
        "select_all": "✅ Select All",
        "deselect_all": "❌ Deselect All",
        "confirm_yes": "✅ Yes",
        "confirm_no": "❌ No",
        "success": "✅ Success",
        "error": "❌ Error",
        "delete_confirm": "Delete {count} item(s)?",
        "delete_selected_button": "🗑 Delete selection ({count})",
        "status_label": "Status:",
        "trial_started": "✅ Your {days}-day free trial has started!\nIt ends on {end_date}.\n\nEnjoy the bot!",
        "menu_prompt": "Choose an option:",
        "trial_expired": "⏰ Your 3-day trial has ended.\n\nTo continue using the bot, contact @DevSculpt to get your permanent license.\n\nThank you for your interest!",
        "main_menu_welcome": "Welcome! Choose an option:",
        "main_menu_group_mgmt": "👥 Manage groups",
        "main_menu_scheduled": "📅 Schedule sends",
        "main_menu_reminders": "⏰ Set reminders",
        "group_config_choice": "Select configuration type:",
        "group_config_welcome": "💬 Welcome message",
        "group_config_antispam": "🛡 Anti-spam protection",
        "group_list_title": "Your eligible groups:",
        "group_list_empty": "No eligible groups found.",
        "group_list_refresh": "🔄 Refresh",
        "welcome_config_title": "Welcome message configuration: {group}",
        "welcome_edit_button": "✏️ Edit message",
        "welcome_edit_prompt": "✏️ Welcome message for {group}\nVariables: {{username}} (name), {{group_name}} (group).\nEnter the new message:",
        "welcome_current_message": "Status: {status}\nMessage: \"{message}\"",
        "welcome_status_enabled": "✅ Enabled",
        "welcome_status_disabled": "❌ Disabled",
        "antispam_config_title": "🛡 Anti-spam: {group}",
        "antispam_block_links": "  🔗  Block links",
        "antispam_block_repeated": "🔁 Block repetitions",
        "antispam_status_enabled": "✅ Enabled",
        "antispam_status_disabled": "❌ Disabled",
        "scheduler_main_title": "📅 Scheduled Messages\nChoose an action:",
        "scheduler_main_create": " ➕ New scheduled message",
        "scheduler_main_edit": "✍️ Edit scheduled message",
        "scheduler_main_delete": "🗑️ Delete scheduled messages",
        "scheduler_create_group_select": "Select target groups:",
        "scheduler_create_text_prompt": "✏️ Enter the message text:",
        "scheduler_create_interval_prompt": "⏱️ Enter the interval between sends (in minutes):\nMinimum: {minimum} minutes.",
        "scheduler_create_count_prompt": "🔢 Enter the maximum number of sends:\n⚠️ Automatic stop after 24 hours, even if the count is not reached.",
        "scheduler_confirm_text": "📋 Summary\n\n📌 Destination: {destination}\n💬 Message: \"{text}\"\n⏱️ Interval: {interval} min\n🔢 Max sends: {count}\n\n⚠️ Automatic stop after 24 hours.\nConfirm?",
        "scheduler_confirm_destination": "{count} group(s) selected",
        "scheduler_confirm_create_button": "✅ Confirm send",
        "scheduler_confirm_edit_button": "✅ Save changes",
        "scheduler_edit_list_title": "📋 Active scheduled messages:",
        "scheduler_edit_list_empty": "No scheduled messages.",
        "scheduler_edit_item_summary": "{text} ({interval}min, {sent}/{max_sends}, {group_count} group(s))",
        "scheduler_edit_text_prompt": "✏️ Current text: \"{current}\"\nEnter a new text or press Continue.",
        "scheduler_edit_interval_prompt": "⏱️ Current interval: {current} min\nEnter a new interval or press Continue.",
        "scheduler_edit_count_prompt": "🔢 Current send count: {current}\nEnter a new count or press Continue.\n⚠️ Automatic stop after 24 hours, even if the count is not reached.",
        "scheduler_delete_list_title": "🗑 Select messages to delete:",
        "scheduler_delete_list_empty": "No scheduled messages to delete.",
        "scheduler_delete_item_summary": "{text} ({interval}min, {sent}/{max_sends}, {group_count} grp)",
        "reminder_main_title": "⏰ Reminders\nChoose an action:",
        "reminder_main_create": " ➕ New Reminder",
        "reminder_main_edit": "✍️ Edit Reminder",
        "reminder_main_delete": "🗑️ Delete Reminder",
        "reminder_mode_prompt": "Select reminder destination:",
        "reminder_mode_private": "📩 Private message",
        "reminder_mode_groups": "👥 Send to groups",
        "reminder_group_select": "Select target groups for the reminder:",
        "reminder_datetime_prompt": "📅 Enter the date and time of the first reminder (format YYYY-MM-DD HH:MM , local time):",
        "reminder_edit_datetime_prompt": "📅 Current date: {current}\nEnter a new date (YYYY-MM-DD HH:MM) or press Continue.",
        "reminder_recurrence_prompt": "🔄 Select recurrence:",
        "reminder_edit_recurrence_prompt": "🔄 Current recurrence: {current}\nChoose a new recurrence or press Continue.",
        "reminder_recurrence_daily": "📆 Daily",
        "reminder_recurrence_weekly": "📅 Weekly",
        "reminder_recurrence_monthly": "🗓 Monthly",
        "reminder_recurrence_once": "1️⃣ Once",
        "reminder_recurrence_short_daily": "Daily",
        "reminder_recurrence_short_weekly": "Weekly",
        "reminder_recurrence_short_monthly": "Monthly",
        "reminder_recurrence_short_once": "Once",
        "reminder_text_prompt": "✏️ Enter the reminder text:",
        "reminder_edit_text_prompt": "✏️ Current text: \"{current}\"\nEnter a new text or press Continue.",
        "reminder_confirm_text": "📋 Summary\n\n📌 Destination: {dest}\n💬 Message: \"{text}\"\n📅 First occurrence: {datetime}\n🔄 Recurrence: {recurrence}\n\nConfirm?",
        "reminder_dest_private": "Private",
        "reminder_dest_groups": "{count} group(s) selected",
        "reminder_confirm_create_button": "✅ Confirm",
        "reminder_confirm_edit_button": "✅ Save changes",
        "reminder_edit_list_title": "📋 Active reminders:",
        "reminder_edit_list_empty": "No reminders.",
        "reminder_delete_list_title": "🗑 Select reminders to delete:",
        "reminder_delete_list_empty": "No reminders to delete.",
        "reminder_delete_item_summary": "{text} ({rec}, {date}, {dest})",
        "success_welcome_updated": "✅ Welcome message updated successfully!",
        "success_scheduler_created": "✅ Scheduled message created successfully!",
        "success_scheduler_edited": "✏️ Scheduled message updated successfully!",
        "success_scheduler_deleted": "🗑 Scheduled message(s) deleted successfully!",
        "success_reminder_created": "✅ Reminder created successfully!",
        "success_reminder_edited": "✏️ Reminder updated successfully!",
        "success_reminder_deleted": "🗑 Reminder(s) deleted successfully!",
        "error_interval_minimum": "❌ Please enter a whole number >= 10 minutes.",
        "error_count_positive": "❌ Please enter a positive whole number.",
        "error_datetime_format": "❌ Invalid or past date. Use the format YYYY-MM-DD HH:MM (e.g. 2026-05-15 14:30).",
        "error_no_eligible_groups": "No eligible groups found.",
        "error_incomplete_data": "Incomplete data.",
        "error_no_selection": "Please select at least one group.",
        "error_message_not_found": "Message not found.",
        "error_no_selection_message": "No message selected.",
        "error_reminder_not_found": "Reminder not found.",
        "error_no_reminder_selected": "No reminder selected.",
        "error_unknown_recurrence": "Unknown recurrence.",
        "error_date_past": "The date is already in the past. Please enter a future date.",
        "welcome_default": "Welcome {username}!"
    }
}


def t(key_path: str, lang: str = "fr", **kwargs) -> str:
    """Récupère un texte localisé avec formatage optionnel.
    Si la langue n'est pas 'fr', l'anglais est utilisé par défaut.
    """
    if lang != "fr":
        lang = "en"
    keys = key_path.split(".")
    value = TEXTS.get(lang, TEXTS["en"])
    for key in keys:
        if isinstance(value, dict) and key in value:
            value = value[key]
        else:
            return key_path
    if kwargs:
        try:
            return value.format(**kwargs)
        except KeyError:
            return value
    return value